services:

  # Nginx Service
  nginx:
    container_name: nginx-service
    image: nginx:1.25.5-alpine
    ports:
      - 9380:8080
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/app.conf
      - .:/var/www/app-service
    depends_on:
      - app
    networks:
      - gt-network

  # APP/API Service
  app:
    container_name: app-service
    build:
      context: ./
      dockerfile: .docker/Dockerfile.app
    working_dir: /var/www/app-service
    volumes:
      - ./:/var/www/app-service
    environment:
      APP_NAME: URL Shortener
      APP_DEBUG: "true"
      APP_KEY: base64:3m9S3/scMcPOeXQVHDk+K/fh9rJ86sL3BKC/jzf4K0o=
      DB_HOST: database
      DB_PORT: 3306
      DB_CONNECTION: mysql
      DB_DATABASE: gt-database
      DB_USERNAME: gt-user
      DB_PASSWORD: gt-password
      REDIS_CLIENT: predis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: gt-password
      REDIS_PREFIX: gt_
      WAIT_HOSTS: database:3306
      WAIT_TIMEOUT: 60
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
    networks:
      - gt-network

  # Database Service
  database:
    container_name: mysql-service
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9306:3306
    volumes:
      - gt-mysql:/var/lib/mysql
      - ./.docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gt-database
      MYSQL_PASSWORD: gt-password
      MYSQL_USER: gt-user
    networks:
      - gt-network

  # Redis Service
  redis:
    container_name: redis-service
    image: redis:6.2.6-alpine
    ports:
      - 9379:6379
    command: ["sh", "-c", "redis-server --appendonly yes --requirepass \"gt-password\""]
    networks:
      - gt-network

#Networks
networks:
  gt-network:
    driver: bridge

#Volumes
volumes:
  gt-mysql:
    driver: local
